import type { Publication } from './types'

export const placeholderPublications: Publication[] = [
  {
    id: 'pub-1',
    title: '[Publication Title Placeholder]',
    authors: ['[Author Placeholder]', '[Author Placeholder]', '[Author Placeholder]'],
    journal: '[Journal Name Placeholder]',
    year: 2024,
    date: 'January 2024',
    type: 'journal',
    abstract: '[Abstract placeholder - This is a placeholder for the publication abstract describing the research methodology, key findings, and conclusions.]',
    tags: ['bioelectronics', 'polymers'],
    doi: '#',
  },
  {
    id: 'pub-2',
    title: '[Publication Title Placeholder]',
    authors: ['[Author Placeholder]', '[Author Placeholder]'],
    journal: '[Journal Name Placeholder]',
    year: 2024,
    date: 'March 2024',
    type: 'journal',
    abstract: '[Abstract placeholder - This is a placeholder for the publication abstract describing the research methodology, key findings, and conclusions.]',
    tags: ['neural interfaces', 'flexible electronics'],
    doi: '#',
  },
  {
    id: 'pub-3',
    title: '[Publication Title Placeholder]',
    authors: ['[Author Placeholder]', '[Author Placeholder]', '[Author Placeholder]', '[Author Placeholder]'],
    journal: '[Conference Name Placeholder]',
    year: 2024,
    date: 'June 2024',
    type: 'conference',
    abstract: '[Abstract placeholder - This is a placeholder for the conference paper abstract describing the presented work and its significance.]',
    tags: ['wearable sensors', 'biocompatibility'],
    doi: '#',
  },
  {
    id: 'pub-4',
    title: '[Publication Title Placeholder]',
    authors: ['[Author Placeholder]', '[Author Placeholder]'],
    journal: '[Preprint Server Placeholder]',
    year: 2024,
    date: 'September 2024',
    type: 'preprint',
    abstract: '[Abstract placeholder - This is a placeholder for the preprint abstract describing preliminary findings and ongoing research.]',
    tags: ['drug delivery', 'hydrogels'],
    doi: '#',
  },
]
